x-yaat-common: &yaat-common
  image: python:3.12-slim
  volumes:
    - .:/repo
  working_dir: /repo
  depends_on:
    - mongo

services:

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo.conf:/etc/mongo.conf:ro
    ports:
      - "27017:27017"
    command: ["mongod", "--config", "/etc/mongo.conf"]

  yaat:
    <<: *yaat-common
    depends_on:
      - mongo
    command: /bin/sh -c "pip install -e . && python main.py"
    healthcheck:
      test: ["CMD", "python", "-m", "httpie", "localhost:8000"]
      interval: 2s
      timeout: 2s
      retries: 30

  yaat-unit-test:
    <<: *yaat-common
    command: /bin/sh -c "pip install -e '.[test]' && pytest tests/unit"
