x-yaat-common: &yaat-common
  image: python:3.12-slim
  volumes:
    - .:/repo
  working_dir: /repo
  depends_on:
    - mongo

services:

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo.conf:/etc/mongo.conf:ro
      - ./storage/db:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--config", "/etc/mongo.conf"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 30s
      timeout: 3s
      retries: 10

  yaat:
    <<: *yaat-common
    depends_on:
      - mongo
    ports:
      - "80:80"
    environment:
      - COINGECKO_KEY=${COINGECKO_KEY:-__no_key__}
      - DOCKER=1
    command: /bin/sh -c "pip install -e . && python main.py"
    healthcheck:
      test: ["CMD", "python", "-m", "httpie", "localhost/heartbeat"]
      interval: 30s
      timeout: 3s
      retries: 10
